

typedef struct m_datetime
{
	unsigned int date;
	unsigned short time;
}DateTime;


#define DATETIME_PARCEL_SIZE_BITS (8)
#define DATETIME_PARCEL_MASK ((1 << DATETIME_PARCEL_SIZE_BITS) -1) // 0xFF
#define DATETIME_DAY_POSITION_BIT (0)
#define DATETIME_MONTH_POSITION_BIT (DATETIME_DAY_POSITION_BIT + DATETIME_PARCEL_SIZE_BITS)
#define DATETIME_YEAR_POSITION_BIT (DATETIME_MONTH_POSITION_BIT + DATETIME_PARCEL_SIZE_BITS)

#define DATETIME_MINUTE_POSITION_BIT (0)
#define DATETIME_HOUR_POSITION_BIT (DATETIME_MINUTE_POSITION_BIT + DATETIME_PARCEL_SIZE_BITS)

DateTime getCurrentDateTime();
void datetimeToString(DateTime dt, char buffer[]);
